# Form implementation generated from reading ui file 'trang_chu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_trang_chu(object):
    def setupUi(self, trang_chu):
        trang_chu.setObjectName("trang_chu")
        trang_chu.resize(580, 503)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/nguye/OneDrive/Hình ảnh/donga.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        trang_chu.setWindowIcon(icon)
        trang_chu.setStyleSheet("")
        self.groupBox = QtWidgets.QGroupBox(parent=trang_chu)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 581, 71))
        self.groupBox.setStyleSheet("background-color: rgba(0, 119, 182,1)\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(170, 10, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.label_image = QtWidgets.QLabel(parent=trang_chu)
        self.label_image.setGeometry(QtCore.QRect(30, 140, 521, 351))
        self.label_image.setText("")
        self.label_image.setPixmap(QtGui.QPixmap("C:/Users/nguye/OneDrive/Hình ảnh/TOTO-100-scaled.jpg"))
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=trang_chu)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 80, 521, 43))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.diemDanh = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.diemDanh.setObjectName("diemDanh")
        self.horizontalLayout.addWidget(self.diemDanh)
        self.dsSinhVien = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.dsSinhVien.setObjectName("dsSinhVien")
        self.horizontalLayout.addWidget(self.dsSinhVien)

        self.retranslateUi(trang_chu)
        QtCore.QMetaObject.connectSlotsByName(trang_chu)

    def retranslateUi(self, trang_chu):
        _translate = QtCore.QCoreApplication.translate
        trang_chu.setWindowTitle(_translate("trang_chu", "Trang chủ"))
        self.label.setText(_translate("trang_chu", "ĐIỂM DANH SINH VIÊN"))
        self.diemDanh.setText(_translate("trang_chu", "Điểm danh"))
        self.dsSinhVien.setText(_translate("trang_chu", "Danh sách sinh viên"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trang_chu = QtWidgets.QWidget()
    ui = Ui_trang_chu()
    ui.setupUi(trang_chu)
    trang_chu.show()
    sys.exit(app.exec())
